apiVersion: v1
kind: Secret
metadata:
  name: greencart-secret
type: Opaque
data:
  MONGODB_URI: <base64>
  JWT_SECRET: <base64>
  CLOUDINARY_API_KEY: <base64>
  STRIPE_SECRET_KEY: <base64>
  STRIPE_WEBHOOK_SECRET: <base64>
  