apiVersion: v1
kind: Secret
metadata:
  name: greencart-secret
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9ub3RvcmlvdXMxOHJqOkN5Ym9yZyU0MDAzMUBjbHVzdGVyMC40eXp3emZkLm1vbmdvZGIubmV0L2dyZWVuY2FydD9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1DbHVzdGVyMA==
  JWT_SECRET: QTl4IVpwJDdxTDJAMA==
  SELLER_PASSWORD: MTIzNDU2Nzg=
  CLOUDINARY_API_KEY: MzU4OTI2NDI5OTU3NzY0
  CLOUDINARY_API_SECRET: cWR5VWt3d2ZnUDV4UU0zX1lzNUVZYnBlRmw=
  STRIPE_SECRET_KEY: c2tfdGVzdF81MVJuZkU4UjE0a0VLdmVDQThkMDFLb1RlTUxrYXVLY2hBYktvRGNuMkY2VGl6b0RLZ3NOV21IRkY0NlBTaWNxVFdQdUQyYjhtZU9CUWF6aVdsZ0hGdVY5MDBGMnFtUTA=
  STRIPE_WEBHOOK_SECRET: d2hzZWNfSVJGUll6SUhudVJsUzNkU2s5bXdNWmk4QVJCSGZGbWg=
  